<?php
namespace Test\Notification\Fields;

use Notification\Fields\GetFields;
use Symfony\Component\Yaml\Yaml;
use Tests\TestCase;

class GetFieldsTest extends TestCase
{
    public function testConstruct()
    {
        /** @var Yaml */
        $yml = $this->getMockBuilder(Yaml::class)
            ->disableOriginalConstructor()
            ->getMock();

        $field = new GetFields($yml);

        $this->assertSame($yml, $field->getYaml());
    }

}

class GetFieldsMock extends GetFields
{
    public function getSource(): array
    {
        return parent::getSource(); // TODO: Change the autogenerated stub
    }
}